### ISSUE TITLE
stack failed on deployment 

### ISSUE THREAD

**Issue by ogerber93** [aws-samples/aws-shield-advanced-one-click-deployment#13]
<img width="1032" alt="image" src="https://github.com/aws-samples/aws-shield-advanced-one-click-deployment/assets/123296665/fed2d753-5b98-4f0d-980e-f76f5ecbc097">

i tried to use Org deployment and ou deployment the parameter is not passed

**Comment by olsonian** [comment]
would you mind emailing me (olsonian@amazon.com) the exact parameter that were present for the top level stack when this occurred

```
aws cloudformation describe-stacks --stack-name aws-shield-advanced-one-click-deploy --query "Stacks[0].Parameters"
