### ISSUE TITLE
Stack create failed S3IAMDelivereRoleStackSet

### ISSUE THREAD

**Issue by berry2012** [aws-samples/aws-shield-advanced-one-click-deployment#14]
ValidationError
Template format error: Unresolved resource dependencies [S3IAMDelivereRoleStackSet] in the Resources block of the template

**Comment by olsonian** [comment]
hi @berry2012.  Can you confirm the 4 AcknowledgeServiceTerms and AcknowledgeServiceNoUnsubscribe parameters are all set to True when you deployed?  S3IAMDelivereRoleStackSet has a condition that all 5 of these are true and doesn't create and causes this type of failure (intentionally) as CFN doesn't have a pre-deploy validation way to stop you from creating the stack if you don't.

If they are all actually true, can you share/email (olsonian@amazon.com) me the results of so I can duplicate/investigate more.

```
aws cloudformation describe-stacks --stack-name aws-shield-advanced-one-click-deploy --query "Stacks[0].Parameters"
```
 
Thanks!

**Comment by berry2012** [comment]
Thank olsonian. All the Acknowledge** parameters were set to True.
I opted for using OUs instead of listing account IDs. I was able to deploy the stack
